# Generated by Django 6.0 on 2025-12-31 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('grade', models.IntegerField(max_length=2)),
                ('address', models.CharField(max_length=255)),
                ('age', models.IntegerField(max_length=3)),
            ],
        ),
    ]
